### ISSUE TITLE
node module just for generic mysqldump?

### ISSUE THREAD

**Issue by gavinengel** [elliotttf/drush-reloadp#11]
I see that this module depends on drush. Are you planning on developing a module for using the mysqldump bin directly in parallel?  (Similar to mydumper.)

**Comment by elliotttf** [comment]
Not presently. The goal of this project was to do the transfer over drush to keep things as simple as possible for drupal developers. A more generic mysqldump project could be modeled after this with relatively little work though. In fact, the [mysql-parallel](https://github.com/deviantintegral/mysql-parallel) project that this was inspired by is pretty close to that already, you'd just have to rewrite it in node.
