### ISSUE TITLE
Support Compression

### ISSUE THREAD

**Issue by robcolburn** [elliotttf/drush-reloadp#3]
I think that we gain a lot with the parallelism, but then we lose a bunch in overall payload vs compressed copies.

Drush [`sql-dump`](http://drush.ws/#sql-dump) has a gzip flag :+1:, but not `sqlc` doesn't :-1:. Would need to route through gunzip, or node [zlib](https://www.npmjs.org/package/zlib).  Aside wonder if node zlib is better/worse than gzip flag. My gut says gzip flag may be able to run on sql-server side which could be faster in many scenarios.

**Comment by elliotttf** [comment]
:+1: Thanks for tracking this in an issue, it's outlined in [code](https://github.com/elliotttf/drush-reloadp/blob/536f7268ddeffcf5084e07eeb5f2239257e13774/index.js#L234) near where it needs to happen too.

As long as the compression is happening on the remote side we'll see a benefit. If it's not then we'd really just be compressing the output after it went over the wire and wouldn't gain much (if anything). The good news is that the dump (the part that goes over the wire) is happening with `sql-dump` so as long as we can pipe the gzipped output into a file directly or into a buffer that node can handle correctly we should be good.

FWIW, I did try this initially but had issues going from gzipped to stdout to child process to buffer to file so put it on the backburner in favor of getting something out there that was usable.

**Comment by elliotttf** [comment]
@robcolburn FYI, this shaved off between 2-5 minutes. Not insignificant but most of the overhead appears to still be on the import.

There's an unrelated bug that I need to fix, but will have a new release up soon.

**Comment by robcolburn** [comment]
The perf gain may be more significant for those behind a great firewall ;-)

:+1: `*` :100:
